from pygame import Vector2 


FPS = 60 
WINDOW_SIZE = Vector2(900, 550) 

NETWORK_SIZE = (2, 4, 2) 
POPULATION = 1000
# NO_OF_VISIBLE_BALLS = 50

MUTATION_CHANCES = 0.1 
MUTATION_MAGNITUDE = 0.2 

# colors 
BACKGROUND_COLOR = (255, 255, 255)
GROUND_COLOR = (0, 0, 0)
WALL_COLOR = (0, 0, 0) 
OBSTACLE_COLOR = (0, 0, 0) 

# events 
from pygame import USEREVENT
SPAWN_OBSTACLE_EVENT = USEREVENT + 1 
UPDATE_GENERATION_EVENT = USEREVENT + 2 
